insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('54562', 340, 'SSD');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('34467', 280, 'HDD');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('32564', 540, 'Procesoare');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('78565', 122, 'Placi de baza');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('45647', 453, 'Placi video');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('23425', 505, 'Memorii RAM');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('87645', 452, 'Surse');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('23474', 657, 'Coolere');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('78945', 756, 'Carcase');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('57356', 574, 'Periferice - Boxe');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('23462', 794, 'Periferice - Mouse');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('78684', 684, 'Periferice - Tastaturi');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('42356', 346, 'Imprimante');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('67454', 856, 'Scannere');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('78558', 876, 'Conectica');
insert into T_CATEGORY (CATEGORY_CODE, QUANTITY, TYPEOFCOMPONENT) values ('57379', 456, 'Utilitare');

insert into T_COMPONENT(MANUFACTURER, PRODUCT_CODE, NAME, PRICE, QUANTITY, CATEGORY_ID) values ('KINGSTON',34242, 'SSD KINGSTON A400', 200, 341, 1);
insert into T_COMPONENT(MANUFACTURER, PRODUCT_CODE, NAME, PRICE, QUANTITY, CATEGORY_ID) values ('Seagate',32526, 'Seagate BarraCuda, 2TB, 7200rpm, 256MB cache, SATA-III', 289, 34, 2);
insert into T_COMPONENT(MANUFACTURER, PRODUCT_CODE, NAME, PRICE, QUANTITY, CATEGORY_ID) values ('Western Digital',75675, 'WD Blue 1TB, 7200rpm, 64MB cache, SATA III', 186, 54, 2);
insert into T_COMPONENT(MANUFACTURER, PRODUCT_CODE, NAME, PRICE, QUANTITY, CATEGORY_ID) values ('AMD',87956, 'AMD Ryzen™ 5 5600X, 35MB, 4.6GHz, Wraith Stealth', 1118, 45, 3);
insert into T_COMPONENT(MANUFACTURER, PRODUCT_CODE, NAME, PRICE, QUANTITY, CATEGORY_ID) values ('ASUS',34587, 'ASUS PRIME B450-PLUS, Socket AM4', 385, 64, 4);
insert into T_COMPONENT(MANUFACTURER, PRODUCT_CODE, NAME, PRICE, QUANTITY, CATEGORY_ID) values ('Gigabyte',76676, 'GeForce® RTX™ 3050 GAMING OC, 8GB GDDR6, 128-bit', 2185, 5, 5);
insert into T_COMPONENT(MANUFACTURER, PRODUCT_CODE, NAME, PRICE, QUANTITY, CATEGORY_ID) values ('Kingston',45364, 'FURY Beast, 16GB DDR4, 3200MHz CL16, Dual Channel Kit', 379, 45, 6);
insert into T_COMPONENT(MANUFACTURER, PRODUCT_CODE, NAME, PRICE, QUANTITY, CATEGORY_ID) values ('Corsair',45364, 'CX Series™ CX750F RGB White, 80 PLUS® Bronze, 750W, Fully Modular', 536, 34, 7);




